global:
  scrape_interval: 15s
 
scrape_configs:
  - job_name: "windows"
    static_configs:
      - targets: ["host.docker.internal:9182"]


  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']
  - job_name: "jenkins"
    metrics_path: /prometheus
    static_configs:
      - targets:
          - jenkins:8080